[package]
name = "nix-store-veritysetup-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
uuid = "1.10.0"
log = "0.4.22"
kernlog = "0.3.1"

[dev-dependencies]
expect-test = "1.5.0"

[profile.release]
opt-level = "s"
panic = "abort"
lto = true
strip = true
